services:
  converter:
    build: app
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/health || exit 1"]
      interval: 3s
      timeout: 2s
      retries: 3